### ISSUE TITLE
generic methods

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#435]
This is a tracking bug for generic methods:

Above the line is P1
- [x] static checking for generic methods (in Analyzer), see #300 
- [x] runtime support in DDC's code generator, see #301 
- [x] SDK uses generic methods, see #434
- [x] instantiated tear-offs, see #525
- [x] async generic methods, see #538

---
- [ ] universal function types, see #526
- [ ] generic function expressions, set #527
- [ ] validate type bounds in dynamic calls, see #532
- [ ] tests for dynamic generic function calls, see #533 
- [ ] improve RTTI representation, see #539
- [ ] language (parser) tests for generic methods, see #535
- [ ] handle generic method overriding a non-generic, see #459

(original discussion & proposal at https://github.com/dart-lang/dev_compiler/issues/28)

**Comment by jmesserly** [comment]
Initial impl is done, I'm going to close this one out, all of the unfinished bugs are still out there and open.
